CREATE TABLE parks_recreation
(
    park_address varchar(255) NOT NULL PRIMARY KEY,
    park_name varchar(50),
    facility varchar(50),
    postal_code varchar(10) NOT NULL,
    FOREIGN KEY (postal_code) references neighbourhood(postal_code)
);


INSERT INTO parks_recreation

VALUES
    ("4202 Valley Drive", "Arbutus Village Park", "Playground", "V6L"),
    ("2995 W 19th Avenue", "Carnarvon Park", "Playground", "V6L"),
    ("4780 Haggart Street", "Prince of Wales Park", "Jogging trail", "V6L"),
    ("4590 Magnolia Street", "Quilchena Park", "Dog Park", "V6L"),
    ("2159 W 36th Avenue", "Ravine Park", "Null", "V6L"),
    ("2610 W 23rd Avenue", "Trafalgar Park", "Playground", "V6L"),
    ("89 Expo Boulevard", "Andy Livingstone Park", "Skateboard Park", "V6B"),
    ("566 Richards Street", "Cathedral Square", "DogPark-Playground", "V6B"),
    ("480 Broughton Street", "Coal Harbour Park", "Null", "V6B"),
    ("1020 Marinaside Crescent", "Coopers Park", "Dog Park-Skateboard Park", "V6B"),
    ("1455 Quebec Street", "Creekside Park", "Null", "V6B"),
    ("1300 Pacific Boulevard", "David Lam Park", "Null", "V6B"),
    ("1929 W Georgia Street", "Devonian Harbour Park", "Null", "V6B"),
    ("625 Burrard Street", "Art Phillips Park", "Null", "V6B"),
    ("1170 Richards Street", "Emery Barnes Park", "Null", "V6B"),
    ("1199 W Cordova Street", "Harbour Green Park", "Null", "V6B"),
    ("1103 Pacific Boulevard", "Helmcken Park", "Null", "V6B"),
    ("1675 Bayshore Drive", "Marina Square", "Null", "V6B"),
    ("801 Beach Avenue", "May & Lorne Brown Park", "Null", "V6B"),
    ("399 Carrall Street", "Pioneer Place", "Null", "V6B"),
    ("1099 W Hastings Street", "Portal Park", "Null", "V6B"),
    ("101 E Waterfront Road", "CRAB Park at Portside", "Null", "V6B"),
    ("181 Roundhouse Mews", "Roundhouse Turntable Plaza", "Null", "V6B"),
    ("578 Carrall Street", "Sun Yat-Sen Gardens", "Null", "V6B"),
    ("200 W Hastings Street", "Victory Square", "Null", "V6B"),
    ("199 Alexander Street", "Wendy Poole Park", "Null", "V6B"),
    ("4594 Balaclava Street", "Balaclava Park", "Dog Park - Running Track - Playground", "V6N"),
    ("4175 Wallace Street", "Chaldecott Park", "Playground", "V6N"),
    ("3530 Deering Island Pl.", "Deering Island Park", "Null", "V6N"),
    ("4701 Dunbar Street", "Memorial West Park", "Playground", "V6N"),
    ("4000 SW Marine Drive", "Musqueam Park", "Dog Park", "V6N"),
    ("3250 Quadra Street", "Quadra West Park", "Null", "V6N"),
    ("3210 W 22nd Avenue", "Valdez Park", "Dog Park", "V6N"),
    ("2400 Spruce Street", "Choklit Park", "Playground", "V5P"),
    ("999 Charleson Street", "Charleson Park", "Dog Park-Playground", "V5P"),
    ("3001 Fir Street", "Granville Park", "Playground", "V5P"),
    ("1318 Cartwright Street", "Sutcliffe Park", "Null", "V5P"),
    ("802 W 7th Avenue", "Willow Park", "Playground", "V5P"),
    ("1775 Woodland Drive", "Alice Townley Park", "Null", "V5L"),
    ("1851 Garden Drive", "Garden Park", "Null", "V5L"),
    ("2125 Victoria Drive", "McSpadden Park", "Playground", "V5L"),
    ("1500 E 8th Avenue", "W.C. Shelley Park", "Playground", "V5L"),
    ("705 Woodland Drive", "Woodland Park", "Null", "V5L"),
    ("2303 Wall Street", "Park Site on Trinity Street", "Null", "V5K"),
    ("1025 Boundary Road", "Adanac Park", "Null", "V5K"),
    ("669 Fellowes Street", "Bates Park", "Null", "V5K"),
    ("650 North Penticton Street", "Burrard View Park", "Playground", "V5K"),
    ("2875 Oxford Street", "Callister Park", "Null", "V5K"),
    ("3400 Charles Street", "Charles Park", "Null", "V5K"),
    ("2690 Grant Street", "Clinton Park", "Playground", "V5K"),
    ("2799 Wall Street", "Dusty Greenwell Park", "Null", "V5K"),
    ("2901 E Hastings", "Hastings Park", "Skateboard Park", "V5K"),
    ("3000 E Pender Street", "Hastings Community Park", "Playground", "V5K"),
    ("2851 E 7th Avenue", "Kaslo Park", "Playground", "V5K"),
    ("3201 New Brighton Road", "New Brighton Park", "Dog Park-Playground", "V5K"),
    ("1600 Rupert Street", "Rupert Park", "Playground", "V5K"),
    ("1950 Windermere Street", "Sunrise Park", "Dog Park-Playground", "V5K"),
    ("3485 E 2nd Avenue", "Thunderbird Park", "Playground", "V5K"),
    ("4175 Victoria Drive", "Brewers Park", "Playground", "V5N"),
    ("2650 Clark Drive", "Cedar Cottage Park", "Playground", "V5N"),
    ("1500 E 14th Avenue", "Clark Park", "Null", "V5N"),
    ("2301 Brock Street", "General Brock Park", "Null", "V5N"),
    ("3999 Glen Drive", "Glen Park", "Playground", "V5N"),
    ("4850 St. Catherines Street", "Grays Park", "Playground", "V5N"),
    ("3300 Victoria Drive", "John Hendry Park", "Dog Park-Playground - Jogging Trail", "V5N"),
    ("5350 Commercial Street", "Jones Park", "Dog Park-Playground", "V5N"),
    ("5175 Dumfries Street", "Kensington Park", "Playground - Skateboard Park", "V5N"),
    ("4150 Knight Street", "Kingcrest Park", "Dog Park-Playground", "V5N"),
    ("1100 E 17th Avenue", "Sunnyside Park", "Playground", "V5N"),
    ("7601 Arbutus Street", "Arbutus Park", "Null", "V6M"),
    ("5800 Elm Street", "Elm Park", "Null", "V6M"),
    ("8705 Angus Drive", "Fraser River Park", "Dog Park", "V6M"),
    ("5898 Yew Street", "Kerrisdale Centennial Park", "Playground", "V6M"),
    ("6001 Balaclava Street", "Malkin Park", "Null", "V6M"),
    ("6875 Yew Street", "Maple Grove Park", "Playground", "V6M"),
    ("6501 Marine Crescent", "McCleery Park", "Null", "V6M"),
    ("7188 Macdonald Street", "McCleery Golf Course", "Null", "V6M"),
    ("2750 E Kent Ave S", "Riverfront Park", "Playground", "V5S"),
    ("3398 E 54th Avenue", "Captain Cook Park", "Null", "V5S"),
    ("3351 Maquinna Drive", "Champlain Heights Park", "Playground", "V5S"),
    ("8200 Kerr Street", "Everett Crowley Park", "Dog Park", "V5S"),
    ("7800 Vivian Drive", "Fraserview Golf Course", "Null", "V5S"),
    ("6205 Kerr Street", "Killarney Park", "Dog Park-Playground", "V5S"),
    ("3350 SE Marine Drive", "Kinross Ravine Park", "Null", "V5S"),
    ("6998 Arlington Street", "Sparwood Park", "Dog Park", "V5S"),
    ("3600 W 12th Avenue", "Almond Park", "Playground", "V6K"),
    ("2390 W 10th Avenue", "Connaught Park", "Playground", "V6K"),
    ("2091 W 7th Avenue", "Delamont Park", "Null", "V6K"),
    ("1905 Ogden Avenue", "Hadden Park", "Dog Park", "V6K"),
    ("1499 Arbutus Street", "Kitsilano Beach Park", "Playground", "V6K"),
    ("2743 Point Grey Road", "Margaret Pigott Park", "Null", "V6K"),
    ("3350 W 4th Avenue", "McBride Park", "Playground", "V6K"),
    ("3215 Point Grey Road", "Point Grey Park Site at Trutch Street", "Null", "V6K"),
    ("1620 Chestnut Street", "Seaforth Peace Park", "Null", "V6K"),
    ("2845 W 3rd Avenue", "Tatlow Park", "Null", "V6K"),
    ("1000 Chestnut Street", "Vanier Park", "Null", "V6K"),
    ("2855 Point Grey Road", "Volunteer Park", "Playground", "V6K"),
    ("8288 Ash Street", "Ash Park", "Playground", "V6P"),
    ("950 W 71st Avenue", "Eburne Park", "Null", "V6P"),
    ("1410 W 72nd Avenue", "Marpole Park", "Playground", "V6P"),
    ("900 W 59th Avenue", "Oak Park", "Playground", "V6P"),
    ("1751 W 66th Avenue", "Riverview Park", "Playground", "V6P"),
    ("1575 W 62nd Avenue", "Shannon Park", "Null", "V6P"),
    ("1592 W 71st Avenue", "William Mackie Park", "Playground", "V6P"),
    ("7575 Columbia Street", "Winona Park", "Playground", "V6P"),
    ("1001 E 7th Avenue", "China Creek North Park", "Playground - Jogging Trail", "V5Y"),
    ("1255 E 10th Avenue", "China Creek South Park", "Skateboard Park", "V5Y"),
    ("2390 Brunswick Street", "Guelph Park", "Playground", "V5Y"),
    ("110 W 7th Avenue", "Jonathan Rogers Park", "Playground", "V5Y"),
    ("2627 Manitoba Street", "Major Matthews Park", "Playground", "V5Y"),
    ("3161 Ontario Street", "Mount Pleasant Park", "Null", "V5Y"),
    ("599 Kingsway", "Robson Park", "Playground", "V5Y"),
    ("266 E 15th Avenue", "Tea Swamp Park", "Playground", "V5Y"),
    ("500 W 54th Avenue", "Cambie Park", "Null", "V5Y"),
    ("5908 Alberta Street", "Columbia Park", "Playground", "V5Y"),
    ("1040 W 43rd Avenue", "Montgomery Park", "Playground", "V5Y"),
    ("6210 Tisdall Street", "Tisdall Park", "Null", "V5Y"),
    ("3215 Slocan Street", "Beaconsfield Park", "Playground", "V5R"),
    ("3450 E 29th Avenue", "Cariboo Park", "Playground", "V5R"),
    ("3450 Price Street", "Carleton Park", "Playground", "V5R"),
    ("5275 McKinnon Street", "Collingwood Park", "Playground", "V5R"),
    ("3434 Falaise Avenue", "Falaise Park", "Dog Park-Playground", "V5R"),
    ("5501 Aberdeen Street", "Foster Park", "Playground", "V5R"),
    ("3470 Crowley Drive", "Gaston Park", "Null", "V5R"),
    ("3650 Price Street", "Price Park", "Null", "V5R"),
    ("2929 E 22nd Avenue", "Renfrew Community Park", "Null", "V5R"),
    ("3900 Renfrew Street", "Renfrew Ravine Park", "Null", "V5R"),
    ("2750 E 29th Avenue", "Slocan Park", "Null", "V5R"),
    ("390 E 36th Avenue", "Cartier Park", "Playground", "V5Y"),
    ("169 E 19th Avenue", "Grimmett Park", "Null", "V5Y"),
    ("4501 Clancy Loranger Way", "Hillcrest Park", "Playground - Jogging Trail", "V5Y"),
    ("4601 Ontario Street", "Nat Bailey Stadium", "Dog Park", "V5Y"),
    ("3773 Prince Edward Street", "Prince Edward Park", "Playground", "V5Y"),
    ("4600 Cambie Street", "Queen Elizabeth Park", "Dog Park", "V5Y"),
    ("50 E 30th Avenue", "Riley Park", "Playground", "V5Y"),
    ("3600 Angus Drive", "Angus Park", "Null", "V6J"),
    ("1250 Devonshire Crescent", "Devonshire Park", "Null", "V6J"),
    ("5670 E Boulevard", "Kerrisdale Park", "Null", "V6J"),
    ("1300 The Crescent", "Shaughnessy Park", "Null", "V6J"),
    ("5251 Oak Street", "VanDusen Botanical Garden", "Null", "V6J"),
    ("895 W 27th Avenue", "Braemar Park", "Null", "V5Z"),
    ("6706 Alberta Street", "Langara Golf Course", "Null", "V5Z"),
    ("801 W 22nd Avenue", "Douglas Park", "Null", "V5Z"),
    ("702 W 18th Avenue", "Heather Park", "Null", "V5Z"),
    ("710 Keefer Street", "MacLean Park", "Null", "V6A"),
    ("400 Powell Street", "Oppenheimer Park", "Null", "V6A"),
    ("857 Malkin Avenue", "Strathcona Park", "Null", "V6A"),
    ("787 Prior Street", "Strathcona Linear Park", "Null", "V6A"),
    ("1166 Main Street", "Thornton Park", "Null", "V6A"),
    ("500 E 63rd Avenue", "George Park", "Dog Park-Playground", "V5X"),
    ("300 E 44th Avenue", "MacDonald Park", "Playground", "V5X"),
    ("5955 Ross Street", "Memorial South Park", "Playground - Jogging Trail", "V5X"),
    ("7646 Prince Albert Street", "Moberly Park", "Playground", "V5X"),
    ("7402 Ross Street", "Ross Park", "Playground", "V5X"),
    ("404 E 51st Avenue", "Sunset Park", "Dog Park-Playground", "V5X"),
    ("2510 Hoylake Avenue", "Bobolink Park", "Playground", "V6P"),
    ("7595 Victoria Drive", "Fraserview Park", "Playground", "V6P"),
    ("2500 E Kent Street S", "Gladstone-Riverside Park", "Null", "V6P"),
    ("6675 Commercial Street", "Gordon Park", "Null", "V6P"),
    ("7250 Humm Street", "Humm Park", "Playground", "V6P"),
    ("2390 E 46th Avenue", "Nanaimo Park", "Playground", "V6P"),
    ("1751 E 45th Avenue", "Tecumseh Park", "Null", "V6P"),
    ("1601 Bayshore Drive", "Cardero Park", "Null", "V6N"),
    ("1755 Beach Avenue", "Alexandra Park", "Null", "V6N"),
    ("1433 Barclay Street", "Barclay Heritage Square", "Null", "V6N"),
    ("1700 Beach Avenue", "English Bay Beach Park", "Null", "V6N"),
    ("1800 Morton Avenue", "Morton Park", "Null", "V6N"),
    ("1030 Bute Street", "Nelson Park", "Dog Park-Playground", "V6N"),
    ("2000 W Georgia Street", "Stanley Park", "Dog Park-Playground-Jogging Trail", "V6N"),
    ("1204 Beach Avenue", "Sunset Beach Park", "Dog Park", "V6N"),
    ("1575 Alma Street", "Hastings Mill Park", "Playground", "V6R"),
    ("3941 Point Grey Road", "Jericho Beach Park", "Null", "V6R"),
    ("4445 NW Marine Drive", "Locarno Park", "Dog Park-Playground", "V6R"),
    ("4801 NW Marine Drive", "Spanish Banks Beach Park", "Dog Park", "V6R"),
    ("2250 Trimble Street", "West Point Grey Park", "Playground", "V6R"),
    ("4651 W 2nd Avenue", "Westmount Park", "Playground", "V6R");