CREATE TABLE TranslinkType
(
    Route varchar(10) PRIMARY KEY,
    Type varchar(128),
    FOREIGN KEY (Route) references translink(Route)
);
INSERT INTO TranslinkType VALUES ("002", "bus");
INSERT INTO TranslinkType VALUES ("003", "bus");
INSERT INTO TranslinkType VALUES ("004", "bus");
INSERT INTO TranslinkType VALUES ("005", "bus");
INSERT INTO TranslinkType VALUES ("006", "bus");
INSERT INTO TranslinkType VALUES ("007", "bus");
INSERT INTO TranslinkType VALUES ("008", "bus");
INSERT INTO TranslinkType VALUES ("009", "bus");
INSERT INTO TranslinkType VALUES ("010", "bus");
INSERT INTO TranslinkType VALUES ("014", "bus");
INSERT INTO TranslinkType VALUES ("016", "bus");
INSERT INTO TranslinkType VALUES ("017", "bus");
INSERT INTO TranslinkType VALUES ("019", "bus");
INSERT INTO TranslinkType VALUES ("020", "bus");
INSERT INTO TranslinkType VALUES ("022", "bus");
INSERT INTO TranslinkType VALUES ("023", "bus");
INSERT INTO TranslinkType VALUES ("025", "bus");
INSERT INTO TranslinkType VALUES ("027", "bus");
INSERT INTO TranslinkType VALUES ("029", "bus");
INSERT INTO TranslinkType VALUES ("032", "bus");
INSERT INTO TranslinkType VALUES ("033", "bus");
INSERT INTO TranslinkType VALUES ("041", "bus");
INSERT INTO TranslinkType VALUES ("042", "bus");
INSERT INTO TranslinkType VALUES ("044", "bus");
INSERT INTO TranslinkType VALUES ("049", "bus");
INSERT INTO TranslinkType VALUES ("050", "bus");
INSERT INTO TranslinkType VALUES ("053", "bus");
INSERT INTO TranslinkType VALUES ("084", "bus");
INSERT INTO TranslinkType VALUES ("095", "bus");
INSERT INTO TranslinkType VALUES ("099", "bus");
INSERT INTO TranslinkType VALUES ("115", "bus");
INSERT INTO TranslinkType VALUES ("137", "bus");
INSERT INTO TranslinkType VALUES ("149", "bus");
INSERT INTO TranslinkType VALUES ("209", "bus");
INSERT INTO TranslinkType VALUES ("210", "bus");
INSERT INTO TranslinkType VALUES ("211", "bus");
INSERT INTO TranslinkType VALUES ("214", "bus");
INSERT INTO TranslinkType VALUES ("216", "bus");
INSERT INTO TranslinkType VALUES ("232", "bus");
INSERT INTO TranslinkType VALUES ("240", "bus");
INSERT INTO TranslinkType VALUES ("241", "bus");
INSERT INTO TranslinkType VALUES ("242", "bus");
INSERT INTO TranslinkType VALUES ("246", "bus");
INSERT INTO TranslinkType VALUES ("247", "bus");
INSERT INTO TranslinkType VALUES ("250", "bus");
INSERT INTO TranslinkType VALUES ("253", "bus");
INSERT INTO TranslinkType VALUES ("254", "bus");
INSERT INTO TranslinkType VALUES ("257", "bus");
INSERT INTO TranslinkType VALUES ("265", "bus");
INSERT INTO TranslinkType VALUES ("287", "bus");
INSERT INTO TranslinkType VALUES ("290", "bus");
INSERT INTO TranslinkType VALUES ("297", "bus");
INSERT INTO TranslinkType VALUES ("323", "bus");
INSERT INTO TranslinkType VALUES ("333", "bus");
INSERT INTO TranslinkType VALUES ("362", "bus");
INSERT INTO TranslinkType VALUES ("381", "bus");
INSERT INTO TranslinkType VALUES ("398", "bus");
INSERT INTO TranslinkType VALUES ("430", "bus");
INSERT INTO TranslinkType VALUES ("453", "bus");
INSERT INTO TranslinkType VALUES ("N8", "bus");
INSERT INTO TranslinkType VALUES ("N9", "bus");
INSERT INTO TranslinkType VALUES ("N10", "bus");
INSERT INTO TranslinkType VALUES ("N15", "bus");
INSERT INTO TranslinkType VALUES ("N17", "bus");
INSERT INTO TranslinkType VALUES ("N19", "bus");
INSERT INTO TranslinkType VALUES ("N20", "bus");
INSERT INTO TranslinkType VALUES ("N22", "bus");
INSERT INTO TranslinkType VALUES ("N24", "bus");
INSERT INTO TranslinkType VALUES ("N35", "bus");
INSERT INTO TranslinkType VALUES ("CL", "skyTrain");
INSERT INTO TranslinkType VALUES ("Expo Line", "skyTrain");
INSERT INTO TranslinkType VALUES ("Millennium Line", "skyTrain");