CREATE TABLE translinkType
(
    route_name varchar(20) PRIMARY KEY,
    route_type varchar(128)
);
INSERT INTO translinkType VALUES ("002", "bus");
INSERT INTO translinkType VALUES ("003", "bus");
INSERT INTO translinkType VALUES ("004", "bus");
INSERT INTO translinkType VALUES ("005", "bus");
INSERT INTO translinkType VALUES ("006", "bus");
INSERT INTO translinkType VALUES ("007", "bus");
INSERT INTO translinkType VALUES ("008", "bus");
INSERT INTO translinkType VALUES ("009", "bus");
INSERT INTO translinkType VALUES ("010", "bus");
INSERT INTO translinkType VALUES ("014", "bus");
INSERT INTO translinkType VALUES ("016", "bus");
INSERT INTO translinkType VALUES ("017", "bus");
INSERT INTO translinkType VALUES ("019", "bus");
INSERT INTO translinkType VALUES ("020", "bus");
INSERT INTO translinkType VALUES ("022", "bus");
INSERT INTO translinkType VALUES ("023", "bus");
INSERT INTO translinkType VALUES ("025", "bus");
INSERT INTO translinkType VALUES ("027", "bus");
INSERT INTO translinkType VALUES ("029", "bus");
INSERT INTO translinkType VALUES ("032", "bus");
INSERT INTO translinkType VALUES ("033", "bus");
INSERT INTO translinkType VALUES ("041", "bus");
INSERT INTO translinkType VALUES ("042", "bus");
INSERT INTO translinkType VALUES ("044", "bus");
INSERT INTO translinkType VALUES ("049", "bus");
INSERT INTO translinkType VALUES ("050", "bus");
INSERT INTO translinkType VALUES ("053", "bus");
INSERT INTO translinkType VALUES ("084", "bus");
INSERT INTO translinkType VALUES ("095", "bus");
INSERT INTO translinkType VALUES ("099", "bus");
INSERT INTO translinkType VALUES ("115", "bus");
INSERT INTO translinkType VALUES ("137", "bus");
INSERT INTO translinkType VALUES ("149", "bus");
INSERT INTO translinkType VALUES ("209", "bus");
INSERT INTO translinkType VALUES ("210", "bus");
INSERT INTO translinkType VALUES ("211", "bus");
INSERT INTO translinkType VALUES ("214", "bus");
INSERT INTO translinkType VALUES ("216", "bus");
INSERT INTO translinkType VALUES ("232", "bus");
INSERT INTO translinkType VALUES ("240", "bus");
INSERT INTO translinkType VALUES ("241", "bus");
INSERT INTO translinkType VALUES ("242", "bus");
INSERT INTO translinkType VALUES ("246", "bus");
INSERT INTO translinkType VALUES ("247", "bus");
INSERT INTO translinkType VALUES ("250", "bus");
INSERT INTO translinkType VALUES ("253", "bus");
INSERT INTO translinkType VALUES ("254", "bus");
INSERT INTO translinkType VALUES ("257", "bus");
INSERT INTO translinkType VALUES ("265", "bus");
INSERT INTO translinkType VALUES ("287", "bus");
INSERT INTO translinkType VALUES ("290", "bus");
INSERT INTO translinkType VALUES ("297", "bus");
INSERT INTO translinkType VALUES ("323", "bus");
INSERT INTO translinkType VALUES ("333", "bus");
INSERT INTO translinkType VALUES ("362", "bus");
INSERT INTO translinkType VALUES ("381", "bus");
INSERT INTO translinkType VALUES ("398", "bus");
INSERT INTO translinkType VALUES ("430", "bus");
INSERT INTO translinkType VALUES ("453", "bus");
INSERT INTO translinkType VALUES ("N8", "bus");
INSERT INTO translinkType VALUES ("N9", "bus");
INSERT INTO translinkType VALUES ("N10", "bus");
INSERT INTO translinkType VALUES ("N15", "bus");
INSERT INTO translinkType VALUES ("N17", "bus");
INSERT INTO translinkType VALUES ("N19", "bus");
INSERT INTO translinkType VALUES ("N20", "bus");
INSERT INTO translinkType VALUES ("N22", "bus");
INSERT INTO translinkType VALUES ("N24", "bus");
INSERT INTO translinkType VALUES ("N35", "bus");
INSERT INTO translinkType VALUES ("Canada Line", "skyTrain");
INSERT INTO translinkType VALUES ("Expo Line", "skyTrain");
INSERT INTO translinkType VALUES ("Millennium Line", "skyTrain");